### PR TITLE
Replacement white spaces

### PR DESCRIPTION
**Pull request by ShadowsAdi**

### CODE REVIEW

**Comment by TheDoctor0** [comment]
To be honest I even forgot that alignment to right in menu is available as it is rarely used.
Unfortunately, right now buymenu does not look as intended:

**Comment by ShadowsAdi** [comment]
I'll test myself it on my server to indent it correctly.

**Comment by TheDoctor0** [comment]
> I'll test myself it on my server to indent it correctly.

Great!

**Comment by regener** [comment]
Even with \R it isn't perfect sadly:



Tabbing would help, but it changes per resolution how it looks.
Maybe listing it like this?
1. [1250] - Weapon name 1 
2. [1500] - Weapon name 2

Prices with 3 numbers could be filled up with a 0 like [0800].

Also it says "Skin $ Cost"
In the weapon menu should it be just "$ Cost"?

**Comment by TheDoctor0** [comment]
It should mimic the default buy menu as close as possible.
It's probably just better to leave it as it.

**Pull request closed without merging**
