### PR TITLE
Turkish Language Added

### PR DESCRIPTION
**Pull request by Snakeren**

### CODE REVIEW

**Comment by TheDoctor0** [comment]
Hi @Snakeren, firstly I want to say - awesome job! Would you be able to also translate [MOTD files](https://github.com/TheDoctor0/CSGOMod/tree/master/cstrike/motd)?
You can commit them to your **patch-1** branch and those changes will be added to this PR.

**Comment by Snakeren** [comment]
> Hi @Snakeren, firstly I want to say - awesome job! Would you be able to also translate [MOTD files](https://github.com/TheDoctor0/CSGOMod/tree/master/cstrike/motd)?
> You can commit them to your **patch-1** branch and those changes will be added to this PR.

Hey it's done. Sorry, i forgot to add it to patch-1. I'm new at this site.

**Comment by TheDoctor0** [comment]
Not really a problem, I added them myself to **patch-1** branch.
I see that one file still needs to be translated: [skins_en.txt](https://github.com/Snakeren/CSGOMod/blob/patch-1/cstrike/motd/skins_en.txt).

**Comment by Snakeren** [comment]
Sorry for late i forgot. It's done

**Comment by TheDoctor0** [comment]
> Sorry for late i forgot.

Don't be sorry, I'm glad that you finished it!

**Review by TheDoctor0 — APPROVED** [review]

**Pull request merged**
